chore: added logo
informatyzacja/strona-organizacji-studenckich pull request #18
Opened 2023-02-12 21:24 UTC by Magouo

2023-02-12 21:25 UTC, Magouo commented
/preview

2023-02-12 21:34 UTC, Byczax requested changes

2023-02-12 21:34 UTC, Byczax commented on src/components/Navbar.tsx
> +import Image from "next/image";
change `import Image` into `import NextImage`

2023-02-12 21:34 UTC, Byczax commented on src/components/Footer.tsx
> +          object-fit="contain"
is there need for this parameter?
Right now every logo is in original size, in the next task there will be need to scale them.

2023-02-12 23:13 UTC, Rei-x requested changes
popraw alty

2023-02-12 23:19 UTC, Omikorin commented
/preview

2023-02-13 20:53 UTC, Byczax approved these changes
ready to merge! 🎉

2023-02-13 20:53 UTC, Rei-x approved these changes
g

2023-02-13 21:00 UTC, Rei-x commented
closes #7

2023-02-13 21:01 UTC, Rei-x commented
fixes #7

2023-02-13 21:03 UTC, merged