feat: add logo
informatyzacja/strona-organizacji-studenckich pull request #30
Opened 2023-02-18 18:30 UTC by Rei-x

2023-02-18 22:25 UTC, Omikorin requested changes

2023-02-18 22:25 UTC, Omikorin commented on src/server/api/file/handler.ts
> +const acceptedImageTypes = ["image/png", "image/jpeg", "image/svg+xml"];
webp could be a good option

2023-02-18 22:44 UTC, Omikorin approved these changes

2023-02-19 00:13 UTC, Omikorin approved these changes

2023-02-19 01:04 UTC, Byczax approved these changes
Git Gud

2023-02-19 14:12 UTC, merged