feat: add crud for tags
informatyzacja/strona-organizacji-studenckich pull request #55
Opened 2023-02-26 18:25 UTC by Rei-x

2023-02-26 18:26 UTC, Rei-x commented
Closes #43

2023-02-26 18:45 UTC, Rei-x commented
Closes #45

2023-02-27 10:07 UTC, Byczax commented
![image](https://user-images.githubusercontent.com/61631855/221533475-bce96180-b37c-400b-8da6-466609ea55a5.png)
Proszę o: 
- zamianę przycisków miejscami
- Zamiast "Zamknij" powinno być "Anuluj"
- ?Mocniejsze wyróżnienie przycisku anulowania (np. underline dla tekstu w przycisku?)
![image](https://user-images.githubusercontent.com/61631855/221534017-8a58066e-c315-47e2-a597-6aee621f56ca.png)
Dodać przycisk "Anuluj" przy tworzeniu taga
![image](https://user-images.githubusercontent.com/61631855/221534187-a6f3cf51-0f4f-4822-8a48-86bdad866e49.png)
Po kliknięciu w taga, prosiłbym o jakieś mocniejsze wyróżnienie taga w headerze, pogrubienie, monospace etc. cokolwiek aby się nie zlewał z resztą

2023-02-27 10:16 UTC, Byczax requested changes

2023-02-27 10:16 UTC, Byczax commented on src/features/admin/views/tags/create.tsx
> +    .max(100, "Tag może mieć maksymalnie 100 znaków"),
Tutaj mnie to zastanawia, gdyż tag powinien być krótki, pamiętliwy i łatwy do zapamiętania, więc na pewno zmieniszyć limit ze 100 na 20-30, np. tag "programowanie" ma 13, jeżeli byśmy chcieli doprecyzować to prędzej lepiej zrobić osobnego taga niż robić dużego taga np. "programowanie obiektowe", te tagi otrzymane od "klienta" są nieodpowiednie, gdyż są zbyt długie i zbyt precyzyjne

2023-02-27 10:16 UTC, Byczax commented on src/features/admin/components/DeleteModal.tsx
> +  );
Wspomniane w komentarzu wyżej

2023-02-27 11:12 UTC, Rei-x commented on src/features/admin/views/tags/index.tsx
> +  // eslint-disable-next-line react-hooks/rules-of-hooks
te rule są już niepotrzebne

2023-02-27 14:36 UTC, Byczax commented on src/features/admin/views/tags/index.tsx
> +    header: () => "Ilość organizacji",
**LICZBA** organizacji!
Ilość dla elementów niepoliczalnych, organizacje są policzalne!

2023-02-27 16:38 UTC, Rei-x commented on src/features/admin/views/tags/index.tsx
> +    header: () => "Ilość organizacji",
a nawet nie wiedziałem, że taka jest zasada, dobrze wyłapane

2023-02-28 11:41 UTC, merged