feat: add and fix all logos' in footer
informatyzacja/strona-organizacji-studenckich pull request #56
Opened 2023-02-26 19:07 UTC by Byczax

closes #47

2023-02-26 19:08 UTC, Rei-x commented
/preview

2023-02-26 19:12 UTC, Rei-x commented
![image](https://user-images.githubusercontent.com/38581479/221431621-ec8e32c3-dcef-4854-967e-9d81571f57de.png)
jest ucięte i dlaczego dałes tutaj czcionke szeryfową, jak cała apka jest sans serif

2023-02-26 19:39 UTC, Rei-x requested changes
popraw logo

2023-02-26 19:42 UTC, Byczax commented
> popraw logo

U mnie działa
![image](https://user-images.githubusercontent.com/61631855/221433179-c793a64b-5688-48f2-941e-82164bcd5b6a.png)

2023-02-26 19:59 UTC, Rei-x commented
> > popraw logo
> 
> U mnie działa ![image](https://user-images.githubusercontent.com/61631855/221433179-c793a64b-5688-48f2-941e-82164bcd5b6a.png)

to jeszcze dodaj te zmiany na brancha

2023-02-26 22:23 UTC, Rei-x commented
> > > > popraw logo
> > > 
> > > 
> > > U mnie działa ![image](https://user-images.githubusercontent.com/61631855/221433179-c793a64b-5688-48f2-941e-82164bcd5b6a.png)
> > 
> > 
> > to jeszcze dodaj te zmiany na brancha
> 
> Tylko że to jest to co teraz jest na branchu, zrobiłem test, w Vivaldi loga się psują, w Firefox działają poprawnie Może tutaj zrobić wyjątek i zamiast svg wrzucić png aby mieć pewność że wyświetli się dobrze?

przekonwertuj tekst na patha i będzie działać

https://linuxhint.com/convert-text-to-path-inkscape/

2023-02-27 10:10 UTC, Byczax commented
/preview

2023-02-27 10:11 UTC, Byczax commented
/preview

2023-02-27 12:26 UTC, Rei-x commented
/preview

2023-02-27 12:30 UTC, Rei-x commented
![image](https://user-images.githubusercontent.com/38581479/221564258-77bc4b0d-01da-41dd-aed4-5cb766caff6c.png)
 
a czemu są dwa loga tutaj

2023-02-27 12:34 UTC, Byczax commented
> ![image](https://user-images.githubusercontent.com/38581479/221564258-77bc4b0d-01da-41dd-aed4-5cb766caff6c.png)
> 
> a czemu są dwa loga tutaj

Aaaa, zapomniałem usunąć, testowałem różne sposoby generowania svg

2023-02-28 12:34 UTC, Rei-x approved these changes

2023-02-28 12:34 UTC, merged